# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QHeaderView,
    QLCDNumber, QLabel, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QSizePolicy, QStatusBar,
    QTabWidget, QTableView, QTreeView, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(604, 524)
        MainWindow.setMinimumSize(QSize(604, 524))
        MainWindow.setMaximumSize(QSize(604, 524))
        icon = QIcon()
        icon.addFile(u"free-icon-repair-6289217.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionSlow = QAction(MainWindow)
        self.actionSlow.setObjectName(u"action_2")
        self.actionSlow.setCheckable(True)
        self.actionMedium = QAction(MainWindow)
        self.actionMedium.setObjectName(u"action_3")
        self.actionMedium.setCheckable(True)
        self.actionFast = QAction(MainWindow)
        self.actionFast.setObjectName(u"action_4")
        self.actionFast.setCheckable(True)
        self.actionFast.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setStyleSheet(u"background-color: rgb(227, 227, 227);")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 31, 16))
        self.widgetGraph = QWidget(self.tab)
        self.widgetGraph.setObjectName(u"widgetGraph")
        self.widgetGraph.setGeometry(QRect(250, -2, 300, 101))
        self.widgetGraph.setMinimumSize(QSize(300, 150)) # efef
        self.progressBarCPU = QProgressBar(self.tab)
        self.progressBarCPU.setObjectName(u"progressBarCPU")
        self.progressBarCPU.setGeometry(QRect(160, 10, 81, 111))
        self.progressBarCPU.setStyleSheet(u"border-top-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.progressBarCPU.setValue(0)
        self.progressBarCPU.setOrientation(Qt.Vertical)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(540, 105, 31, 21))
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 10, 21, 16))
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 100, 71, 21))
        font = QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.lcdNumberCPU = QLCDNumber(self.tab)
        self.lcdNumberCPU.setStyleSheet(u"background-color: rgb(255, 255, 255); border-color: rgb(0, 0, 0)")
        self.lcdNumberCPU.setObjectName(u"lcdNumberCPU")
        self.lcdNumberCPU.setGeometry(QRect(90, 100, 64, 21))
        self.labelCPU = QLabel(self.tab)
        self.labelCPU.setWordWrap(True)
        self.labelCPU.setObjectName(u"labelCPU")
        self.labelCPU.setGeometry(QRect(10, 30, 141, 51))
        font1 = QFont()
        font1.setBold(True)
        self.labelCPU.setFont(font1)
        self.labelCPU.setCursor(QCursor(Qt.PointingHandCursor))
        self.line = QFrame(self.tab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 120, 581, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 31, 16))
        self.lcdNumberRAM = QLCDNumber(self.tab)
        self.lcdNumberRAM.setStyleSheet(u"background-color: rgb(255, 255, 255); border-color: rgb(0, 0, 0)")
        self.lcdNumberRAM.setObjectName(u"lcdNumberRAM")
        self.lcdNumberRAM.setGeometry(QRect(90, 230, 64, 23))
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 230, 71, 21))
        self.label_7.setFont(font)
        self.progressBarRAM = QProgressBar(self.tab)
        self.progressBarRAM.setObjectName(u"progressBarRAM")
        self.progressBarRAM.setGeometry(QRect(160, 140, 81, 111))
        self.progressBarRAM.setStyleSheet(u"border-top-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.progressBarRAM.setValue(0)
        self.progressBarRAM.setTextVisible(True)
        self.progressBarRAM.setOrientation(Qt.Vertical)
        self.progressBarRAM.setTextDirection(QProgressBar.TopToBottom)
        self.progressBarRAM2 = QProgressBar(self.tab)
        self.progressBarRAM2.setObjectName(u"progressBarRAM2")
        self.progressBarRAM2.setGeometry(QRect(280, 190, 291, 61))
        self.progressBarRAM2.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.progressBarRAM2.setValue(0)
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 160, 131, 16))
        self.labelRAM = QLabel(self.tab)
        self.labelRAM.setObjectName(u"labelRAM")
        self.labelRAM.setGeometry(QRect(20, 190, 131, 31))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(340, 160, 211, 16))
        self.label_8.setFont(font)
        self.line_2 = QFrame(self.tab)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 260, 581, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 280, 151, 16))
        self.treeViewDisc = QTreeView(self.tab)
        self.treeViewDisc.setObjectName(u"treeViewDisc")
        self.treeViewDisc.setGeometry(QRect(10, 300, 561, 131))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tableViewProc = QTableView(self.tab_2)
        self.tableViewProc.setObjectName(u"tableViewProc")
        self.tableViewProc.setGeometry(QRect(10, 10, 561, 421))
        self.tableViewProc.setStyleSheet(u"selection-background-color: rgb(200, 200, 200);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tableViewProcSlujbi = QTableView(self.tab_3)
        self.tableViewProcSlujbi.setObjectName(u"tableViewProcSlujbi")
        self.tableViewProcSlujbi.setGeometry(QRect(10, 10, 561, 421))
        self.tableViewProcSlujbi.setStyleSheet(u"selection-background-color: rgb(190, 190, 190);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tableViewProcTasks = QTableView(self.tab_4)
        self.tableViewProcTasks.setObjectName(u"tableViewProcTasks")
        self.tableViewProcTasks.setGeometry(QRect(10, 10, 561, 421))
        self.tableViewProcTasks.setStyleSheet(u"selection-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_4, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 604, 22))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menu)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
#if QT_CONFIG(shortcut)
#endif // QT_CONFIG(shortcut)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.menu_2.menuAction())
        self.menu_2.addAction(self.actionSlow)
        self.menu_2.addAction(self.actionMedium)
        self.menu_2.addAction(self.actionFast)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u0414\u0438\u0441\u043f\u0435\u0442\u0447\u0435\u0440 \u0437\u0430\u0434\u0430\u0447", None))
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        MainWindow.setWindowFilePath("")
        self.actionSlow.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0438\u0437\u043a\u0430\u044f", None))
        self.actionMedium.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0440\u0435\u0434\u043d\u044f\u044f", None))
        self.actionFast.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0441\u043e\u043a\u0430\u044f", None))
#if QT_CONFIG(statustip)
        self.tabWidget.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(accessibility)
        self.label.setAccessibleName(QCoreApplication.translate("MainWindow", u"hyhh", None))
#endif // QT_CONFIG(accessibility)
        self.label.setText(QCoreApplication.translate("MainWindow", u"CPU:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"justify\">\u0421\u0435\u043a.</p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0433\u0440\u0443\u0437\u043a\u0430:", None))
        self.labelCPU.setText(QCoreApplication.translate("MainWindow", u"", None))
#if QT_CONFIG(accessibility)
        self.label_6.setAccessibleName(QCoreApplication.translate("MainWindow", u"hyhh", None))
#endif // QT_CONFIG(accessibility)
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RAM:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0433\u0440\u0443\u0437\u043a\u0430:", None))
        # self.progressBarRAM2.setFormat(QCoreApplication.translate("MainWindow", u"%pГБ/%mГБ", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0431\u0449\u0438\u0439 \u043e\u0431\u044a\u0451\u043c \u043f\u0430\u043c\u044f\u0442\u0438:", None))
        self.labelRAM.setText(QCoreApplication.translate("MainWindow", u"Обновление...", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e/\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f (\u0413\u0431):", None))
#if QT_CONFIG(accessibility)
        self.label_9.setAccessibleName(QCoreApplication.translate("MainWindow", u"hyhh", None))
#endif // QT_CONFIG(accessibility)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u0438\u0441\u043a\u0430\u0445", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u0411\u044b\u0441\u0442\u0440\u043e\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0446\u0435\u0441\u0441\u044b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u0421\u043b\u0443\u0436\u0431\u044b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0434\u0430\u0447\u0438", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u0412\u0438\u0434", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f", None))
    # retranslateUi

